include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    cancel_subscriptions: false
    avoid_shadowing_type_parameters: false
    await_only_futures: true
    always_declare_return_types: true
    close_sinks: true
    comment_references: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    prefer_final_in_for_each: true
    prefer_single_quotes: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    avoid_type_to_string: true
    no_leading_underscores_for_local_identifiers: false
    sort_child_properties_last: false
